databases:
  - name: burgername # Nombre correcto
    plan: free
    databaseName: burgername # Nombre correcto
    # user: pola7188 # Quita esta línea para que Render maneje el usuario

services:
  - type: web
    plan: free
    name: HamburguesasApp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn HamburguesasApp.asgi:application -k uvicorn.workers.UvicornWorker" # Nombre correcto
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: burgername # Nombre correcto
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4