services:
  - type: web
    name: hamburguesas-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn HamburguesasApp.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "hamburguesas-app.onrender.com"
    staticDir: ./staticfiles